roles:
  - name: member
    parent: null
    permissions:
      - CallCharacter
      - GetHelp
      - GetCharacterList
  - name: moderator
    parent: member
    permissions: []
  - name: administrator
    parent: moderator
    permissions: []
  - name: Mod - La Table Ronde
    parent: moderator
    permissions: []
  - name: Mod - Bartender
    parent: moderator
    permissions: []
  - name: Mod - Croupier
    parent: moderator
    permissions: []
  - name: Admin - Conseil de Guerre
    parent: administrator
    permissions: []
  - name: PÃ©dÃ¨stres seniors
    parent: member
    permissions: []
    type: Clan
    description: Ils sont vieux et ils vont en marchant !
  - name: Semi Croustillants
    parent: member
    permissions: []
    type: Clan
    description: Pas complÃ¨tement mais a moitie quand mÃªme !
  - name: IndÃ©pendantistes Gallois
    parent: member
    permissions: []
    type: Clan
    description: Gallois ou Gaulois ? Mais indÃ©pendants avant tout !
  - name: Team Chateau
    parent: member
    permissions: []
    type: Clan
    description: Iels sont fort(e)s, c'est un roc, non c'est des rocs, c'est un chateau
  - name: Aeterniens
    parent: member
    permissions: []
    type: Group
    description: (ğŸ“œ-new-world) Toi aussi pars a la dÃ©couverte d'un New World
  - name: Vikingerus
    parent: member
    permissions: []
    type: Group
    description: (ğŸ›¶-valheim) Valhalla mais aussi ici avec ton drakkar
  - name: Cochonou
    parent: member
    permissions: []
    type: Group
    description: (ğŸš«-nsfw) Toi aussi tu aimes les cochonneries ? (En rejoignant se
      rÃ´le, tu valides avoir 18ans)
  - name: PokemonCatcher
    parent: member
    permissions: []
    type: Group
    description: (âš¡-pokemon) Attrapez les tous !
  - name: Loliste
    parent: member
    permissions: []
    type: Group
    description: (Runeterra Prime) On se marre pas ici, on est dans la faille !
  - name: PoliticalLeader
    parent: member
    permissions: []
    type: Group
    description: (ğŸŒ-grande-strategie) Moins langue de bois, et aucune scrupule politique
  - name: Cubiste
    parent: member
    permissions: []
    type: Group
    description: (â›-minecraft) Des cubes !! Des cubes partooooouuut !
  - name: RtsPoin
    parent: member
    permissions: []
    type: Group
    description: (ğŸ¥-rts) Age of Poinpoin, et aussi les autres.
  - name: RocketLeagueruu
    parent: member
    permissions: []
    type: Group
    description: (ğŸš—-rocket-league) vroum vroum but !
  - name: Viewer
    parent: member
    permissions: []
    type: Group
    description: (Regarder les autres) Nous aussi on a des streamers ! pEvent !
  - name: Sans-Entraves
    parent: member
    permissions: []
    type: Group
    description: (ğŸ§™ Azeroth ğŸ§™) Wow wow wow keep calm et viens mythic
  - name: Roliste
    parent: member
    permissions: []
    type: Group
    description: (ğŸŒ²La foret ğŸŒ²) Du papier et des dÃ©s, que demande le peuple ?
  - name: Valolo
    parent: member
    permissions: []
    type: Group
    description: (Valorant) CS poinpoin mais avec des pouvoirs ?
  - name: CroixBatonVÃ©
    parent: member
    permissions: []
    type: Group
    description: (ğŸ¤º-feufeugaz-croixbatonvÃ©) FeuFeu c'est le Feu ! Limsa Lominsa !
  - name: SpaceSurfing
    parent: member
    permissions: []
    type: Group
    description: (Open Space Cookies) Un open space pour Ãªtre dÃ©rangÃ©(e) comme au boulot
